// aufgabe-01/b__angular-layout/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'b__angular-layout';
}

<app-holy-grail-layout>

    <app-dummy-block slot="top" bg="red">
        Content-Top
    </app-dummy-block>


    <app-dummy-block slot="center-left" bg="cornflowerblue" [maxHeight]="true">
        Center-Left
    </app-dummy-block>

    <app-dummy-block slot="center-center" bg="powderblue" [maxHeight]="true">
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center<br/>
        Center-Center
    </app-dummy-block>

    <app-dummy-block slot="center-right" bg="royalblue" [maxHeight]="true">
        Center-Right
    </app-dummy-block>


    <app-dummy-block slot="bottom" bg="red">
        Content-Bottom
    </app-dummy-block>

</app-holy-grail-layout>

// aufgabe-01/d__react-layout-css-in-js/src/App.tsx
import React from 'react';

import { DummyBlock }      from 'Components/DummyBlock';
import { HolyGrailLayout } from 'Components/HolyGrailLayout';

export const App = () => {
    
    const Top    = () => <DummyBlock bg={ 'red' }>Content-Top</DummyBlock>;
    const Bottom = () => <DummyBlock bg={ 'red' }>Content-Bottom</DummyBlock>;
    const Left   = () => <DummyBlock bg={ 'cornflowerblue' } maxHeight={ true }>Content-Left</DummyBlock>;
    const Right  = () => <DummyBlock bg={ 'royalblue' } maxHeight={ true }>Content-Right</DummyBlock>;
    const Center = () => <DummyBlock bg={ 'powderblue' } maxHeight={ true }>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center<br/>
        Content-Center
    </DummyBlock>
    
    return <HolyGrailLayout
        top={ <Top/> }
        centerLeft={ <Left/> }
        centerCenter={ <Center/> }
        centerRight={ <Right/> }
        bottom={ <Bottom/> }
    />;
}

export default App;
